### ISSUE TITLE
Unable to use SDNS stamp

### ISSUE THREAD

**Issue by radiumatic** [bepass-org/bepass#24]
I'm trying to use a SDNS stamp from dnscrypt-proxy serverlist, needless to say, it probably is valid

But in the logs:
```
socksLogger2023/08/09 20:45:06 2023-08-09 20:45:06 [E]: server: illegal base64 data at input byte 123
```
Using termux and proot to run linux armv7 build

**Comment by nimagp** [comment]
> please send your config.json i will look into it

It's pretty much the defaults except for the DNS. 

I tried multiple SDNS stamps (dnscrypt protocol) from this link: https://dnscrypt.info/public-servers/

Works if I use a DoH

**Comment by uoosef** [comment]
Yes i tested it its clearly a bug i will fix it within a day

**Comment by uoosef** [comment]
unfortunately official sdns v2 library doesnt support custom dialer in golang. so i need help to resolve this issue

**Comment by nimagp** [comment]
> unfortunately official sdns v2 library doesnt support custom dialer in golang. so i need help to resolve this issue

I'm not familiar with golang, but assuming "hacking around" the library internal APIs is not a suitable solution, isn't it just better at this point to create an issue in sdns repository?

**Comment by DanielcoderX** [comment]
> unfortunately official sdns v2 library doesnt support custom dialer in golang. so i need help to resolve this issue

which one do you mean **[dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy)** or **[sdns](https://github.com/semihalev/sdns)** ?
both are based on Go and they are accessible for future improvement.
